<a href="https://colab.research.google.com/github/worldterminator/worldterminator/blob/main/becomingmaster.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
vera = pd.read_csv("/incarceration_trends_county.csv", dtype=str)

print("Shape:", vera.shape)
print("Columns:", vera.columns.tolist()[:30])
print("\nSample rows:")
display(vera.head(10))

# check years
print("\nUnique years in dataset:")
print(vera['year'].unique()[:20])   # first 20 unique values

# count number of counties per year
coverage = vera.groupby('year')["fips"].nunique()
print("\nCounty coverage by year:")
print(coverage.sort_index())

Shape: (245840, 146)
Columns: ['year', 'quarter', 'state_abbr', 'state_code', 'state_fips', 'county_name', 'county_code', 'fips', 'urbanicity', 'region', 'division', 'metro_area_2000', 'commuting_zone_2000', 'land_area_2000', 'total_pop', 'total_pop_15to64', 'female_pop_15to64', 'male_pop_15to64', 'aapi_pop_15to64', 'black_pop_15to64', 'latinx_pop_15to64', 'native_pop_15to64', 'white_pop_15to64', 'aapi_female_pop_15to64', 'black_female_pop_15to64', 'latinx_female_pop_15to64', 'native_female_pop_15to64', 'white_female_pop_15to64', 'aapi_male_pop_15to64', 'black_male_pop_15to64']

Sample rows:

,year,quarter,state_abbr,state_code,state_fips,county_name,county_code,fips,urbanicity,region,...,aapi_female_prison_adm_rate,black_female_prison_adm_rate,latinx_female_prison_adm_rate,native_female_prison_adm_rate,white_female_prison_adm_rate,aapi_male_prison_adm_rate,black_male_prison_adm_rate,latinx_male_prison_adm_rate,native_male_prison_adm_rate,white_male_prison_adm_rate
0,2024,1,AL,US_AL,AL,Autauga County,US_AL_AUTAUGA,01001,small/mid,South,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023,4,AL,US_AL,AL,Autauga County,US_AL_AUTAUGA,01001,small/mid,South,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023,3,AL,US_AL,AL,Autauga County,US_AL_AUTAUGA,01001,small/mid,South,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023,2,AL,US_AL,AL,Autauga County,US_AL_AUTAUGA,01001,small/mid,South,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023,1,AL,US_AL,AL,Autauga County,US_AL_AUTAUGA,01001,small/mid,South,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2022,4,AL,US_AL,AL,Autauga County,US_AL_AUTAUGA,01001,small/mid,South,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2022,3,AL,US_AL,AL,Autauga County,US_AL_AUTAUGA,01001,small/mid,South,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2022,2,AL,US_AL,AL,Autauga County,US_AL_AUTAUGA,01001,small/mid,South,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2022,1,AL,US_AL,AL,Autauga County,US_AL_AUTAUGA,01001,small/mid,South,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2021,4,AL,US_AL,AL,Autauga County,US_AL_AUTAUGA,01001,small/mid,South,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Unique years in dataset:
['2024' '2023' '2022' '2021' '2020' '2019' '2018' '2017' '2016' '2015'
 '2014' '2013' '2012' '2011' '2010' '2009' '2008' '2007' '2006' '2005']

County coverage by year:
year
1970    3142
1971    3142
1972    3142
1973    3142
1974    3142
1975    3142
1976    3142
1977    3142
1978    3142
1979    3142
1980    3142
1981    3142
1982    3142
1983    3142
1984    3142
1985    3142
1986    3142
1987    3142
1988    3142
1989    3142
1990    3142
1991    3142
1992    3142
1993    3142
1994    3142
1995    3142
1996    3142
1997    3142
1998    3142
1999    3142
2000    3142
2001    3142
2002    3142
2003    3142
2004    3142
2005    3142
2006    3142
2007    3142
2008    3142
2009    3142
2010    3142
2011    3142
2012    3142
2013    3142
2014    3142
2015    3142
2016    3142
2017    3142
2018    3142
2019    3142
2020    3142
2021    3142
2022    3142
2023    3142
2024    1488
Name: fips, dtype: int64

In [3]:
print(vera_2022_q4.dtypes.to_string())

year                              object
quarter                           object
state_abbr                        object
state_code                        object
state_fips                        object
county_name                       object
county_code                       object
fips                              object
urbanicity                        object
region                            object
division                          object
metro_area_2000                   object
commuting_zone_2000               object
land_area_2000                   float64
total_pop                        float64
total_pop_15to64                 float64
female_pop_15to64                float64
male_pop_15to64                  float64
aapi_pop_15to64                  float64
black_pop_15to64                 float64
latinx_pop_15to64                float64
native_pop_15to64                float64
white_pop_15to64                 float64
aapi_female_pop_15to64           float64
black_female_pop_15to64          float64
latinx_female_pop_15to64         float64
native_female_pop_15to64         float64
white_female_pop_15to64          float64
aapi_male_pop_15to64             float64
black_male_pop_15to64            float64
latinx_male_pop_15to64           float64
native_male_pop_15to64           float64
white_male_pop_15to64            float64
total_incarceration              float64
total_incarceration_rate         float64
private_jail_flag                float64
regional_jail_flag               float64
jail_rated_capacity              float64
total_jail_pop                   float64
female_jail_pop                  float64
male_jail_pop                    float64
aapi_jail_pop                    float64
black_jail_pop                   float64
latinx_jail_pop                  float64
native_jail_pop                  float64
white_jail_pop                   float64
other_race_jail_pop              float64
total_jail_pretrial              float64
total_jail_from_prison           float64
total_jail_from_other_jail       float64
total_jail_from_fed              float64
total_jail_from_bia              float64
total_jail_from_bop              float64
total_jail_from_ice              float64
total_jail_from_marshals         float64
total_jail_from_other_fed        float64
total_jail_adm                   float64
female_jail_adm                  float64
male_jail_adm                    float64
total_jail_dis                   float64
total_jail_sentenced             float64
total_jail_pop_rate              float64
female_jail_pop_rate             float64
male_jail_pop_rate               float64
aapi_jail_pop_rate               float64
black_jail_pop_rate              float64
latinx_jail_pop_rate             float64
native_jail_pop_rate             float64
white_jail_pop_rate              float64
total_jail_adm_rate              float64
female_jail_adm_rate             float64
male_jail_adm_rate               float64
total_jail_dis_rate              float64
total_jail_pretrial_rate         float64
total_prison_pop                 float64
female_prison_pop                float64
male_prison_pop                  float64
aapi_prison_pop                  float64
black_prison_pop                 float64
latinx_prison_pop                float64
native_prison_pop                float64
white_prison_pop                 float64
aapi_female_prison_pop           float64
black_female_prison_pop          float64
latinx_female_prison_pop         float64
native_female_prison_pop         float64
white_female_prison_pop          float64
aapi_male_prison_pop             float64
black_male_prison_pop            float64
latinx_male_prison_pop           float64
native_male_prison_pop           float64
white_male_prison_pop            float64
total_prison_adm                 float64
female_prison_adm                float64
male_prison_adm                  float64
aapi_prison_adm                  float64
black_prison_adm                 float64
latinx_prison_adm                float64
native_prison_adm                float64
white_prison_adm                 float64
aapi_female_prison_adm           float64
black_female_prison_adm          float64
latinx_female_prison_adm         float64
native_female_prison_adm         float64
white_female_prison_adm          float64
aapi_male_prison_adm             float64
black_male_prison_adm            float64
latinx_male_prison_adm           float64
native_male_prison_adm           float64
white_male_prison_adm            float64
total_prison_pop_rate            float64
female_prison_pop_rate           float64
male_prison_pop_rate             float64
aapi_prison_pop_rate             float64
black_prison_pop_rate            float64
latinx_prison_pop_rate           float64
native_prison_pop_rate           float64
white_prison_pop_rate            float64
aapi_female_prison_pop_rate      float64
black_female_prison_pop_rate     float64
latinx_female_prison_pop_rate    float64
native_female_prison_pop_rate    float64
white_female_prison_pop_rate     float64
aapi_male_prison_pop_rate        float64
black_male_prison_pop_rate       float64
latinx_male_prison_pop_rate      float64
native_male_prison_pop_rate      float64
white_male_prison_pop_rate       float64
total_prison_adm_rate            float64
female_prison_adm_rate           float64
male_prison_adm_rate             float64
aapi_prison_adm_rate             float64
black_prison_adm_rate            float64
latinx_prison_adm_rate           float64
native_prison_adm_rate           float64
white_prison_adm_rate            float64
aapi_female_prison_adm_rate      float64
black_female_prison_adm_rate     float64
latinx_female_prison_adm_rate    float64
native_female_prison_adm_rate    float64
white_female_prison_adm_rate     float64
aapi_male_prison_adm_rate        float64
black_male_prison_adm_rate       float64
latinx_male_prison_adm_rate      float64
native_male_prison_adm_rate      float64
white_male_prison_adm_rate       float64

In [8]:
import pandas as pd
import numpy as np

YEAR = "2022"
QUARTER = "2"
vera_2022_q2 = vera[(vera["year"] == YEAR) & (vera["quarter"] == QUARTER)].copy()

# id string
id_cols = [
    "year", "quarter", "state_abbr", "state_code", "state_fips",
    "county_name", "county_code", "fips", "urbanicity", "region",
    "division", "metro_area_2000", "commuting_zone_2000"
]
# standardize FIPS
if "fips" in vera_2022_q2.columns:
    vera_2022_q2["fips"] = vera_2022_q2["fips"].astype(str).str.zfill(5)

num_cols = [c for c in vera_2022_q2.columns if c not in id_cols]
vera_2022_q2[num_cols] = vera_2022_q2[num_cols].apply(pd.to_numeric, errors="coerce")

In [12]:
# check coverage of pretrial count vs rate by quarter
v22 = vera[vera["year"] == "2022"].copy()
tbl = (v22
       .groupby("quarter")
       .agg(
           rows=("fips","count"),
           nonmissing_pretrial=("total_jail_pretrial", lambda s: int(s.notna().sum())),
           nonmissing_pretrial_rate=("total_jail_pretrial_rate", lambda s: int(s.notna().sum())),
       )
       .assign(
           pct_pretrial=lambda d: d["nonmissing_pretrial"]/d["rows"],
           pct_pretrial_rate=lambda d: d["nonmissing_pretrial_rate"]/d["rows"],
       )
       .sort_index())
print(tbl)

         rows  nonmissing_pretrial  nonmissing_pretrial_rate  pct_pretrial  \
quarter
1        1565                  698                       698      0.446006
2        3142                 1065                      1065      0.338956
3        1536                  650                       650      0.423177
4        1503                  635                       635      0.422488

         pct_pretrial_rate
quarter
1                 0.446006
2                 0.338956
3                 0.423177
4                 0.422488

In [9]:
# make new variables!
# total_pop as denominator as requested

den_col = "total_pop" if "total_pop" in vera_2022_q2.columns else None

def safe_div(n, d):
    n = pd.to_numeric(n, errors="coerce")
    d = pd.to_numeric(d, errors="coerce")
    return np.where((d.notna()) & (d != 0), n / d, np.nan)

# Rates won't error; rows with missing/zero denom become NaN
vera_2022_q2["pretrial_rate_100k"] = (
    safe_div(vera_2022_q2["total_jail_pretrial"], vera_2022_q2[den_col]) * 1e5
    if den_col else np.nan
)

vera_2022_q2["pretrial_share"] = safe_div(
    vera_2022_q2["total_jail_pretrial"], vera_2022_q2["total_jail_pop"]
)
# keep everything (all jail/prison/admissions/race fields) for merge later
vera_keep = vera_2022_q2.copy()

/tmp/ipython-input-1075089169.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vera_2022_q2["pretrial_rate_100k"] = (
/tmp/ipython-input-1075089169.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vera_2022_q2["pretrial_share"] = safe_div(

In [10]:
df = vera_keep
# light health checks
if "pretrial_share" in df:
    share_lt0 = df["pretrial_share"] < 0
    share_gt1 = df["pretrial_share"] > 1
    print("pretrial_share < 0:", int(share_lt0.sum()))
    print("pretrial_share > 1:", int(share_gt1.sum()))
    print("pretrial_share missing:", int(df["pretrial_share"].isna().sum()))

pretrial_gt_total = df["total_jail_pretrial"] > df["total_jail_pop"]
print("pretrial > total_jail_pop:", int(pretrial_gt_total.sum()))

den_bad = df["total_jail_pop"].isna() | (df["total_jail_pop"] <= 0)
print("non-positive or missing total_jail_pop:", int(den_bad.sum()))

pretrial_share < 0: 0
pretrial_share > 1: 0
pretrial_share missing: 2077
pretrial > total_jail_pop: 0
non-positive or missing total_jail_pop: 1109

In [11]:
print("Rows, Cols:", vera_keep.shape)
display(vera_keep[["fips","county_name","state_abbr","total_jail_pop","total_jail_pretrial",
                   den,"pretrial_rate_100k","pretrial_share"]].head())

Rows, Cols: (3142, 148)

,fips,county_name,state_abbr,total_jail_pop,total_jail_pretrial,total_pop_15to64,pretrial_rate_100k,pretrial_share
7,01001,Autauga County,AL,153.0,143.0,38587.0,239.294500,0.934641
85,01003,Baldwin County,AL,719.0,547.0,150739.0,221.965224,0.760779
151,01005,Barbour County,AL,72.0,4.0,15529.0,16.190399,0.055556
218,01007,Bibb County,AL,NaN,NaN,14530.0,NaN,NaN
282,01009,Blount County,AL,NaN,NaN,37127.0,NaN,NaN

In [ ]:
#vera_keep["pretrial_rate_100k_zerofill"] = vera_keep["pretrial_rate_100k"].fillna(0)
#vera_keep["pretrial_share_zerofill"]     = vera_keep["pretrial_share"].fillna(0)

# (alternative optional) zero-fill all numeric columns (leave object/id columns alone)
# import numpy as np
# num_cols = vera_keep.select_dtypes(include=[np.number]).columns
# vera_keep[num_cols] = vera_keep[num_cols].fillna(0)

# export
vera_keep.to_csv("vera_2022_q2_snapshot_with_newvars.csv", index=False)

#slavery

In [6]:
import pandas as pd
enslaved = pd.read_csv("/content/nhgis0002_ds13_1860_county.csv")
totalpop = pd.read_csv("/content/nhgis0002_ds14_1860_county.csv")

enslaved = enslaved.iloc[1:].copy()
totalpop = totalpop.iloc[1:].copy()

# to numeric
enslaved["AGU001"] = pd.to_numeric(enslaved["AGU001"], errors="coerce")
totalpop["AG3001"] = pd.to_numeric (totalpop ["AG3001"], errors="coerce")

In [7]:
# quick inspection
print("Enslaved 1860:")
print(enslaved.head(), "\n")
print(enslaved.info(), "\n")

print("Total Pop 1860:")
print(totalpop.head(), "\n")
print(totalpop.info(), "\n")

Enslaved 1860:
    GISJOIN  YEAR    STATE STATEA   COUNTY COUNTYA AREANAME STATEICP  \
1  G0100010  1860  Alabama    010  Autauga    0010  Autauga       41
2  G0100030  1860  Alabama    010  Baldwin    0030  Baldwin       41
3  G0100050  1860  Alabama    010  Barbour    0050  Barbour       41
4  G0100070  1860  Alabama    010     Bibb    0070     Bibb       41
5  G0100090  1860  Alabama    010   Blount    0090   Blount       41

  COUNTYICP   AGU001
1        10   9607.0
2        30   3714.0
3        50  16150.0
4        70   3842.0
5        90    666.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2098 entries, 1 to 2098
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GISJOIN    2098 non-null   object
 1   YEAR       2098 non-null   object
 2   STATE      2098 non-null   object
 3   STATEA     2098 non-null   object
 4   COUNTY     2098 non-null   object
 5   COUNTYA    2098 non-null   object
 6   AREANAME   2098 non-null   object
 7   STATEICP   2098 non-null   object
 8   COUNTYICP  2098 non-null   object
 9   AGU001     1130 non-null   float64
dtypes: float64(1), object(9)
memory usage: 164.0+ KB
None

Total Pop 1860:
    GISJOIN  YEAR    STATE STATEA   COUNTY COUNTYA AREANAME STATEICP  \
1  G0100010  1860  Alabama    010  Autauga    0010  Autauga       41
2  G0100030  1860  Alabama    010  Baldwin    0030  Baldwin       41
3  G0100050  1860  Alabama    010  Barbour    0050  Barbour       41
4  G0100070  1860  Alabama    010     Bibb    0070     Bibb       41
5  G0100090  1860  Alabama    010   Blount    0090   Blount       41

  COUNTYICP   AG3001
1        10  16739.0
2        30   7530.0
3        50  30812.0
4        70  11894.0
5        90  10865.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2102 entries, 1 to 2102
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GISJOIN    2102 non-null   object
 1   YEAR       2102 non-null   object
 2   STATE      2102 non-null   object
 3   STATEA     2102 non-null   object
 4   COUNTY     2102 non-null   object
 5   COUNTYA    2102 non-null   object
 6   AREANAME   2102 non-null   object
 7   STATEICP   2102 non-null   object
 8   COUNTYICP  2102 non-null   object
 9   AG3001     2077 non-null   float64
dtypes: float64(1), object(9)
memory usage: 164.3+ KB
None

In [8]:
enslaved = enslaved.rename(columns={"AGU001": "enslaved_1860"})
totalpop = totalpop.rename(columns={"AG3001": "total_pop_1860"})

In [9]:
merged = (
    enslaved[["GISJOIN","STATE","COUNTY","STATEA","COUNTYA","enslaved_1860"]]
      .merge(totalpop[["GISJOIN","total_pop_1860"]], on="GISJOIN", how="outer")
)

In [11]:
import numpy as np
merged["slave_share_1860"] = merged["enslaved_1860"] / merged["total_pop_1860"]
merged.loc[(merged["total_pop_1860"].fillna(0) == 0), "slave_share_1860"] = np.nan

In [12]:
# derive 5-digit FIPS from STATEA+COUNTYA
# e.g. STATEA='010' -> '01'; COUNTYA='0010' -> '001'  => fips='01001'
merged["fips"] = merged["STATEA"].str[:2].fillna("") + merged["COUNTYA"].str[:3].fillna("")
merged["fips"] = merged["fips"].where(merged["fips"].str.len() == 5, np.nan)

In [13]:
for col in ["STATE","COUNTY"]:
    if col in merged.columns:
        merged[col] = merged[col].str.upper().str.strip()

In [14]:
print("Row counts → enslaved:", len(enslaved), " total:", len(totalpop), " merged:", len(merged))
print("\nMissing after merge:\n", merged[["enslaved_1860","total_pop_1860","slave_share_1860","fips"]].isna().sum())

Row counts → enslaved: 2098  total: 2102  merged: 2105

Missing after merge:
 enslaved_1860       975
total_pop_1860       28
slave_share_1860    976
fips                  7
dtype: int64

In [15]:
# what didn’t match
only_ensl = enslaved[~enslaved["GISJOIN"].isin(totalpop["GISJOIN"])][["GISJOIN","STATE","COUNTY"]]
only_tot  = totalpop[~totalpop["GISJOIN"].isin(enslaved["GISJOIN"])][["GISJOIN"]]
print("\nOnly in enslaved:", len(only_ensl))
print("Only in totalpop:", len(only_tot))

Only in enslaved: 3
Only in totalpop: 7

In [16]:
print("\nRows only in enslaved:")
print(only_ensl)

print("\nRows only in totalpop:")
print(only_tot)

Rows only in enslaved:
       GISJOIN                 STATE                COUNTY
163   G1100010  District Of Columbia  District Of Columbia
1195  G3150435    Nebraska Territory               Madison
1201  G3150575    Nebraska Territory                Platte

Rows only in totalpop:
       GISJOIN
187   G1200875
628   G2050055
862   G2405100
1202  G3150585
1208  G3150695
1710  G4800590
1859  G4950655

In [17]:
# random spot chekcks
print(merged.sample(5, random_state=42)[["fips","STATE","COUNTY","enslaved_1860","total_pop_1860","slave_share_1860"]])

# highest and lowest slave shares
print(merged.sort_values("slave_share_1860", ascending=False)
             [["fips","STATE","COUNTY","enslaved_1860","total_pop_1860","slave_share_1860"]]
             .head(5))

       fips           STATE     COUNTY  enslaved_1860  total_pop_1860  \
1432  39065            OHIO     HARDIN            NaN         13570.0
342   17019        ILLINOIS  CHAMPAIGN            NaN         14629.0
984   27115       MINNESOTA       PINE            NaN            92.0
2007  51179        VIRGINIA   STAFFORD         3314.0          8555.0
1342  37065  NORTH CAROLINA  EDGECOMBE        10108.0         17376.0

      slave_share_1860
1432               NaN
342                NaN
984                NaN
2007          0.387376
1342          0.581722
       fips        STATE      COUNTY  enslaved_1860  total_pop_1860  \
1023  28055  MISSISSIPPI   ISSAQUENA         7244.0          7831.0
1057  28151  MISSISSIPPI  WASHINGTON        14467.0         15679.0
788   22029    LOUISIANA   CONCORDIA        12542.0         13805.0
817   22107    LOUISIANA      TENSAS        14592.0         16078.0
799   22065    LOUISIANA     MADISON        12477.0         14133.0

      slave_share_1860
1023          0.925042
1057          0.922699
788           0.908511
817           0.907576
799           0.882827

In [20]:
ready = merged[["fips","enslaved_1860","total_pop_1860","slave_share_1860"]].copy()

ready.to_csv("nhgis_1860_share.csv", index=False),list(ready.columns)

(None, ['fips', 'enslaved_1860', 'total_pop_1860', 'slave_share_1860'])

RUCC

In [5]:
import pandas as pd

acs = pd.read_csv("/acs_county_2022.csv")

# utf-8encoding(default) didn't work. trying a forgiving encoding for RUCC
rucc = pd.read_csv("/Ruralurbancontinuumcodes2023.csv", encoding="latin1")

print(rucc.head())
print(rucc.info())

   FIPS State     County_Name        Attribute  \
0  1001    AL  Autauga County  Population_2020
1  1001    AL  Autauga County        RUCC_2023
2  1001    AL  Autauga County      Description
3  1003    AL  Baldwin County  Population_2020
4  1003    AL  Baldwin County        RUCC_2023

                                               Value
0                                              58805
1                                                  2
2  Metro - Counties in metro areas of 250,000 to ...
3                                             231767
4                                                  3
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9703 entries, 0 to 9702
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   FIPS         9703 non-null   int64
 1   State        9703 non-null   object
 2   County_Name  9703 non-null   object
 3   Attribute    9703 non-null   object
 4   Value        9703 non-null   object
dtypes: int64(1), object(4)
memory usage: 379.2+ KB
None

In [7]:
rucc_wide = rucc.pivot(index="FIPS", columns="Attribute", values="Value").reset_index()

# reshape result
print("\nRUCC wide format:")
print(rucc_wide.head())
print(rucc_wide.info())

RUCC wide format:
Attribute  FIPS                                        Description  \
0          1001  Metro - Counties in metro areas of 250,000 to ...
1          1003  Metro - Counties in metro areas of fewer than ...
2          1005  Nonmetro - Urban population of 5,000 to 20,000...
3          1007  Metro - Counties in metro areas of 1 million p...
4          1009  Metro - Counties in metro areas of 1 million p...

Attribute Population_2020 RUCC_2023
0                   58805         2
1                  231767         3
2                   25223         6
3                   22293         1
4                   59134         1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3235 entries, 0 to 3234
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FIPS             3235 non-null   int64
 1   Description      3235 non-null   object
 2   Population_2020  3235 non-null   object
 3   RUCC_2023        3233 non-null   object
dtypes: int64(1), object(3)
memory usage: 101.2+ KB
None

In [8]:
print("\nACS 2022 file head:")
print(acs.head())

print("\nACS 2022 file columns:")
print(list(acs.columns))

ACS 2022 file head:
   pct_under_18  pct_65plus  pct_hispanic  pct_black  pct_aian  pct_asian  \
0          23.4        15.6           2.2       96.8      72.6       19.6
1          21.2        21.2           3.7       95.2      82.3        8.3
2          20.7        19.8           5.2       95.2      44.6       46.9
3          21.2        16.8           1.0       97.1      74.2       20.7
4          23.0        18.3           4.6       90.3      85.7        1.2

   pct_foreign_born  pct_limited_english  pct_poverty  med_hh_income  ...  \
0               1.9                 96.3          8.3          68315  ...
1               1.0                 95.1          7.0          71039  ...
2               0.4                 92.1         20.8          39712  ...
3               1.1                 97.5         16.3          50669  ...
4               0.5                 92.1         10.2          57440  ...

   pct_broadband_sub  pop_total  gini_index  state_fips  county_fips  geoid  \
0               89.1      58761      0.4541           1            1   1001
1               88.9     233420      0.4648           1            3   1003
2               68.2      24877      0.5098           1            5   1005
3               79.7      22251      0.4553           1            7   1007
4               82.7      59077      0.4475           1            9   1009

                      name  land_sqmi  pop_total.1  pop_density_per_sqmi
0  Autauga County, Alabama    594.455        58761             98.848525
1  Baldwin County, Alabama   1589.863       233420            146.817682
2  Barbour County, Alabama    885.008        24877             28.109350
3     Bibb County, Alabama    622.470        22251             35.746301
4   Blount County, Alabama    644.891        59077             91.607729

[5 rows x 46 columns]

ACS 2022 file columns:
['pct_under_18', 'pct_65plus', 'pct_hispanic', 'pct_black', 'pct_aian', 'pct_asian', 'pct_foreign_born', 'pct_limited_english', 'pct_poverty', 'med_hh_income', 'pct_unemployed', 'pct_in_labor_force', 'pct_less_than_hs', 'pct_ba_plus', 'pct_snap_households', 'pct_uninsured', 'pct_disability', 'pct_female_head_fam_with_children', 'pct_single_parent_hh', 'pct_owner_occupied', 'pct_renter_occupied', 'housing_vacancy_rate', 'pct_overcrowded_gt1pproom', 'pct_lacking_complete_kitchen', 'pct_lacking_complete_plumbing', 'median_gross_rent', 'pct_rent_ge_30pct_income', 'median_home_value', 'pct_zero_vehicles', 'mean_travel_time_minutes', 'pct_commute_drive_alone', 'pct_commute_carpool', 'pct_commute_public_transit', 'pct_commute_walk', 'pct_commute_other', 'pct_work_from_home', 'pct_broadband_sub', 'pop_total', 'gini_index', 'state_fips', 'county_fips', 'geoid', 'name', 'land_sqmi', 'pop_total.1', 'pop_density_per_sqmi']

In [9]:
# geoid → 5-digit 'fips' string with leading z~e~r~o~
acs["fips"] = acs["geoid"].astype(str).str.zfill(5)

print(acs[["geoid","fips"]].head())

   geoid   fips
0   1001  01001
1   1003  01003
2   1005  01005
3   1007  01007
4   1009  01009